
/******************************************************************************
 * This file was auto-generated by welds. 
 * changes to this file will be overridden when Welds generate runs again.
******************************************************************************/


#[derive(Debug, Clone)]
pub struct People {
    pub id: Option<i32>,
    pub name: Option<String>,
    pub farts: Option<u8>,
}
