/******************************************************************************
 * This file was auto-generated by welds-cli.
 * changes to this file will be overridden when the welds-cli generate command runs again.
******************************************************************************/

use welds::WeldsModel;
#[derive(Debug, WeldsModel)]
#[welds(schema = "welds", table = "Persons")]
pub struct Person {
    #[welds(primary_key)]
    #[welds(rename = "PersonID")]
    pub person_id: i32,
    #[welds(rename = "Address")]
    pub address: Option<String>,
    #[welds(rename = "City")]
    pub city: Option<String>,
    #[welds(rename = "FirstName")]
    pub first_name: Option<String>,
    #[welds(rename = "LastName")]
    pub last_name: Option<String>,
}
