
/******************************************************************************
 * This file was auto-generated by welds-cli. 
 * changes to this file will be overridden when the welds-cli generate command runs again.
******************************************************************************/


use welds::WeldsModel;
#[derive(Debug, sqlx :: FromRow, WeldsModel)]
#[welds(db(Postgres))]
#[welds(schema = "public", table = "orders")]
pub struct Order {
    #[welds(primary_key)]
    pub id: i64,
    pub sold_for: f64,
    pub code: String,
    pub product_id: i32,
    pub quantity: i16,
}
