/******************************************************************************
 * This file was auto-generated by welds-cli.
 * changes to this file will be overridden when the welds-cli generate command runs again.
******************************************************************************/

use welds::WeldsModel;
#[derive(Debug, WeldsModel)]
#[welds(schema = "public", table = "orders")]
#[welds(BelongsTo(product, super::super::product::Product, "product_id"))]
pub struct Order {
    #[welds(primary_key)]
    pub id: i64,
    #[welds(rename = "SoldFor")]
    pub sold_for: Option<f64>,
    pub code: Option<String>,
    pub product_id: Option<i32>,
    pub quantity: Option<i16>,
}
