/******************************************************************************
 * This file was auto-generated by welds-cli.
 * changes to this file will be overridden when the welds-cli generate command runs again.
******************************************************************************/

use welds::WeldsModel;
#[derive(Debug, sqlx :: FromRow, WeldsModel)]
#[welds(db(Mssql))]
#[welds(schema = "welds", table = "Orders")]
#[welds(BelongsTo(product, super::super::product::Product, "product_id"))]
#[welds(BelongsTo(product2, super::super::product::Product, "product_id2"))]
pub struct Order {
    #[welds(primary_key)]
    pub id: i32,
    pub product_id: i32,
    #[sqlx(rename = "product_id2")]
    pub product_id_2: Option<i32>,
}
