/******************************************************************************
 * This file was auto-generated by welds-cli.
 * changes to this file will be overridden when the welds-cli generate command runs again.
 *
 * If you want to take control of this file and prevent welds-cli from overriding it,
 * You can set the flag `manual_update: true` for this table in the welds.yaml config.
******************************************************************************/

use welds::WeldsModel;
#[derive(Debug, sqlx :: FromRow, WeldsModel, Default)]
#[welds(db(Postgres))]
#[welds(schema = "alt", table = "table_with_arrays")]
pub struct TableWithArray {
    #[welds(primary_key)]
    pub id: i32,
    pub numbers: Vec<i32>,
}
