
/******************************************************************************
 * This file was auto-generated by welds-cli. 
 * changes to this file will be overridden when the welds-cli generate command runs again.
******************************************************************************/


use welds::WeldsModel;
#[derive(Debug, sqlx :: FromRow, WeldsModel)]
#[welds(db(Postgres))]
#[welds(schema = "alt", table = "others")]
pub struct Other {
    #[welds(primary_key)]
    pub id: i32,
}
