
/******************************************************************************
 * This file was auto-generated by welds-cli. 
 * changes to this file will be overridden when the welds-cli generate command runs again.
******************************************************************************/


mod definition;
pub use definition::*;
