/******************************************************************************
 * This file was auto-generated by welds-cli.
 * changes to this file will be overridden when the welds-cli generate command runs again.
******************************************************************************/

use welds::WeldsModel;
#[derive(Debug, sqlx :: FromRow, WeldsModel)]
#[welds(db(Mssql))]
#[welds(schema = "welds", table = "Products")]
#[welds(HasMany(order, super::super::order::Order, "product_id"))]
#[welds(HasMany(order2, super::super::order::Order, "product_id2"))]
pub struct Product {
    #[welds(primary_key)]
    #[sqlx(rename = "ID")]
    pub id: i32,
    pub active: Option<i32>,
    #[sqlx(rename = "Description")]
    pub description: Option<String>,
    pub name: String,
    #[sqlx(rename = "price1")]
    pub price_1: Option<f32>,
    #[sqlx(rename = "price2")]
    pub price_2: Option<f32>,
}
