
/******************************************************************************
 * This file was auto-generated by welds-cli. 
 * changes to this file will be overridden when the welds-cli generate command runs again.
******************************************************************************/


use welds::WeldsModel;
#[derive(Debug, sqlx :: FromRow, WeldsModel)]
#[welds(db(Postgres))]
#[welds(schema = "public", table = "products")]
#[welds(HasMany(order, super::super::order::Order, "product_id"))]
pub struct Product {
    #[welds(primary_key)]
    pub product_id: i32,
    pub active: Option<bool>,
    pub barcode: Option<Vec<u8>>,
    pub description: Option<String>,
    pub name: String,
    #[sqlx(rename = "price1")]
    pub price_1: Option<f32>,
    #[sqlx(rename = "price2")]
    pub price_2: Option<f64>,
    #[sqlx(rename = "price3")]
    pub price_3: Option<sqlx::postgres::types::PgMoney>,
}
