/******************************************************************************
 * This file was auto-generated by welds-cli.
 * changes to this file will be overridden when the welds-cli generate command runs again.
******************************************************************************/

use welds::WeldsModel;

#[derive(Debug, sqlx::FromRow, WeldsModel, PartialEq)]
#[welds(schema = "public", table = "Products")]
#[welds(HasMany(order, super::super::order::Order, "product_id"))]
pub struct Product {
    #[welds(primary_key)]
    pub product_id: i32,
    pub active: Option<bool>,
    pub barcode: Option<Vec<u8>>,
    pub description: Option<String>,
    pub name: String,
    #[welds(rename = "price1")]
    #[sqlx(rename = "price1")]
    pub price_1: Option<f32>,
    #[welds(rename = "price2")]
    #[sqlx(rename = "price2")]
    pub price_2: Option<f64>,
    #[welds(rename = "price3")]
    #[sqlx(rename = "price3")]
    pub price_3: Option<sqlx::postgres::types::PgMoney>,
}

// Used to test finding table/model diffs

#[derive(Debug, WeldsModel)]
#[welds(schema = "bad_schema_name", table = "products")]
#[welds(HasMany(order, super::super::order::Order, "product_id"))]
pub struct BadProductMissingTable {
    #[welds(primary_key)]
    pub product_id: i32,
    pub active: Option<bool>,
    pub barcode: Option<Vec<u8>>,
    pub description: Option<String>,
    pub name: String,
    #[welds(rename = "price1")]
    pub price_1: Option<f32>,
    #[welds(rename = "price2")]
    pub price_2: Option<f64>,
    #[welds(rename = "price3")]
    pub price_3: Option<sqlx::postgres::types::PgMoney>,
}

#[derive(Debug, WeldsModel)]
#[welds(db(Postgres))]
#[welds(schema = "public", table = "Products")]
#[welds(HasMany(order, super::super::order::Order, "product_id"))]
pub struct BadProductColumns {
    #[welds(primary_key)]
    pub product_id: i64, // type should be i32
    pub active: bool, // null was removed
    pub barcode: Option<Vec<u8>>,
    pub description2: Option<String>, // column name is wrong
    pub name: Option<String>,         // null was added
    #[welds(rename = "price1")]
    pub price_1: Option<f32>,
    #[welds(rename = "price2")]
    pub price_2: Option<f64>,
    #[welds(rename = "price3")]
    pub price_3: Option<sqlx::postgres::types::PgMoney>,
}
